import Head from "next/head";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  const GA_MEASUREMENT_ID = process.env.GA_MEASUREMENT_ID;

  return (
    <div className={styles.container}>
      <Head>
        <title>Google Analytics with NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Lets implement Google Analytics with NextJS
        </h1>
      </main>

      <Script
        id="google-analytics-first-script"
        type="text/partytown"
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
      />

      <Script
        id="google-analytics-second-script"
        type="text/partytown"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            window.gtag = function gtag(){window.dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}', {
              page_path: window.location.pathname,
            });
          `,
        }}
      />
    </div>
  );
}
